// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatums

import "strconv"

type AccountStatusType int32

const (
	AccountStatusTypedefault  AccountStatusType = 0
	AccountStatusTypeactive   AccountStatusType = 1
	AccountStatusTypesuspend  AccountStatusType = 2
	AccountStatusTypedisabled AccountStatusType = 3
	AccountStatusTypedeleted  AccountStatusType = 4
)

var EnumNamesAccountStatusType = map[AccountStatusType]string{
	AccountStatusTypedefault:  "default",
	AccountStatusTypeactive:   "active",
	AccountStatusTypesuspend:  "suspend",
	AccountStatusTypedisabled: "disabled",
	AccountStatusTypedeleted:  "deleted",
}

var EnumValuesAccountStatusType = map[string]AccountStatusType{
	"default":  AccountStatusTypedefault,
	"active":   AccountStatusTypeactive,
	"suspend":  AccountStatusTypesuspend,
	"disabled": AccountStatusTypedisabled,
	"deleted":  AccountStatusTypedeleted,
}

func (v AccountStatusType) String() string {
	if s, ok := EnumNamesAccountStatusType[v]; ok {
		return s
	}
	return "AccountStatusType(" + strconv.FormatInt(int64(v), 10) + ")"
}
