// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatums

import "strconv"

type NotifyType int32

const (
	NotifyTypeUnDefine NotifyType = 0
	NotifyTypeinsert   NotifyType = 1
	NotifyTypeupdate   NotifyType = 2
	NotifyTypedelete   NotifyType = 3
)

var EnumNamesNotifyType = map[NotifyType]string{
	NotifyTypeUnDefine: "UnDefine",
	NotifyTypeinsert:   "insert",
	NotifyTypeupdate:   "update",
	NotifyTypedelete:   "delete",
}

var EnumValuesNotifyType = map[string]NotifyType{
	"UnDefine": NotifyTypeUnDefine,
	"insert":   NotifyTypeinsert,
	"update":   NotifyTypeupdate,
	"delete":   NotifyTypedelete,
}

func (v NotifyType) String() string {
	if s, ok := EnumNamesNotifyType[v]; ok {
		return s
	}
	return "NotifyType(" + strconv.FormatInt(int64(v), 10) + ")"
}
