// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatums

import "strconv"

type OperationType int32

const (
	OperationTypedefault OperationType = 0
	OperationTypeInsert  OperationType = 1
	OperationTypeUpdate  OperationType = 2
	OperationTypeDelete  OperationType = 3
)

var EnumNamesOperationType = map[OperationType]string{
	OperationTypedefault: "default",
	OperationTypeInsert:  "Insert",
	OperationTypeUpdate:  "Update",
	OperationTypeDelete:  "Delete",
}

var EnumValuesOperationType = map[string]OperationType{
	"default": OperationTypedefault,
	"Insert":  OperationTypeInsert,
	"Update":  OperationTypeUpdate,
	"Delete":  OperationTypeDelete,
}

func (v OperationType) String() string {
	if s, ok := EnumNamesOperationType[v]; ok {
		return s
	}
	return "OperationType(" + strconv.FormatInt(int64(v), 10) + ")"
}
