// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatums

import "strconv"

type ServiceStatusType int32

const (
	ServiceStatusTypedefault  ServiceStatusType = 0
	ServiceStatusTypeactive   ServiceStatusType = 1
	ServiceStatusTypesuspend  ServiceStatusType = 2
	ServiceStatusTypedisabled ServiceStatusType = 3
	ServiceStatusTypedeleted  ServiceStatusType = 4
)

var EnumNamesServiceStatusType = map[ServiceStatusType]string{
	ServiceStatusTypedefault:  "default",
	ServiceStatusTypeactive:   "active",
	ServiceStatusTypesuspend:  "suspend",
	ServiceStatusTypedisabled: "disabled",
	ServiceStatusTypedeleted:  "deleted",
}

var EnumValuesServiceStatusType = map[string]ServiceStatusType{
	"default":  ServiceStatusTypedefault,
	"active":   ServiceStatusTypeactive,
	"suspend":  ServiceStatusTypesuspend,
	"disabled": ServiceStatusTypedisabled,
	"deleted":  ServiceStatusTypedeleted,
}

func (v ServiceStatusType) String() string {
	if s, ok := EnumNamesServiceStatusType[v]; ok {
		return s
	}
	return "ServiceStatusType(" + strconv.FormatInt(int64(v), 10) + ")"
}
