// automatically generated by the FlatBuffers compiler, do not modify

package goums.terminal;

public final class NotifyType {
  private NotifyType() { }
  public static final int UnDefine = 0;
  public static final int insert = 1;
  public static final int update = 2;
  public static final int delete = 3;

  public static final String[] names = { "UnDefine", "insert", "update", "delete", };

  public static String name(int e) { return names[e]; }
}

