// automatically generated by the FlatBuffers compiler, do not modify

package goums.terminal;

public final class OperationType {
  private OperationType() { }
  public static final int UnDefine = 0;
  public static final int active = 1;
  public static final int auth = 2;

  public static final String[] names = { "UnDefine", "active", "auth", };

  public static String name(int e) { return names[e]; }
}

