// automatically generated by the FlatBuffers compiler, do not modify

package goums.terminal;

public final class ServiceStatusType {
  private ServiceStatusType() { }
  public static final int default = 0;
  public static final int inStock = 1;
  public static final int active = 2;
  public static final int suspend = 3;
  public static final int disabled = 4;
  public static final int deleted = 5;

  public static final String[] names = { "default", "inStock", "active", "suspend", "disabled", "deleted", };

  public static String name(int e) { return names[e]; }
}

