// automatically generated by the FlatBuffers compiler, do not modify

package goums.terminal;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TerminalList extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_11_1(); }
  public static TerminalList getRootAsTerminalList(ByteBuffer _bb) { return getRootAsTerminalList(_bb, new TerminalList()); }
  public static TerminalList getRootAsTerminalList(ByteBuffer _bb, TerminalList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TerminalList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Count() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateCount(long Count) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, Count); return true; } else { return false; } }
  public goums.terminal.TerminalProfile List(int j) { return List(new goums.terminal.TerminalProfile(), j); }
  public goums.terminal.TerminalProfile List(goums.terminal.TerminalProfile obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int ListLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public goums.terminal.TerminalProfile.Vector ListVector() { return ListVector(new goums.terminal.TerminalProfile.Vector()); }
  public goums.terminal.TerminalProfile.Vector ListVector(goums.terminal.TerminalProfile.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTerminalList(FlatBufferBuilder builder,
      long Count,
      int ListOffset) {
    builder.startTable(2);
    TerminalList.addCount(builder, Count);
    TerminalList.addList(builder, ListOffset);
    return TerminalList.endTerminalList(builder);
  }

  public static void startTerminalList(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addCount(FlatBufferBuilder builder, long Count) { builder.addLong(0, Count, 0L); }
  public static void addList(FlatBufferBuilder builder, int ListOffset) { builder.addOffset(1, ListOffset, 0); }
  public static int createListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTerminalList(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TerminalList get(int j) { return get(new TerminalList(), j); }
    public TerminalList get(TerminalList obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

