// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package terminal

import "strconv"

type OperationType int32

const (
	OperationTypeUnDefine OperationType = 0
	OperationTypeactive   OperationType = 1
	OperationTypeauth     OperationType = 2
)

var EnumNamesOperationType = map[OperationType]string{
	OperationTypeUnDefine: "UnDefine",
	OperationTypeactive:   "active",
	OperationTypeauth:     "auth",
}

var EnumValuesOperationType = map[string]OperationType{
	"UnDefine": OperationTypeUnDefine,
	"active":   OperationTypeactive,
	"auth":     OperationTypeauth,
}

func (v OperationType) String() string {
	if s, ok := EnumNamesOperationType[v]; ok {
		return s
	}
	return "OperationType(" + strconv.FormatInt(int64(v), 10) + ")"
}
