// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package account

import "strconv"

/// Role account's access role define
type Role int8

const (
	RoleGuest  Role = 0
	RoleMember Role = 1
	RoleVIP    Role = 2
)

var EnumNamesRole = map[Role]string{
	RoleGuest:  "Guest",
	RoleMember: "Member",
	RoleVIP:    "VIP",
}

var EnumValuesRole = map[string]Role{
	"Guest":  RoleGuest,
	"Member": RoleMember,
	"VIP":    RoleVIP,
}

func (v Role) String() string {
	if s, ok := EnumNamesRole[v]; ok {
		return s
	}
	return "Role(" + strconv.FormatInt(int64(v), 10) + ")"
}
