// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package account

import "strconv"

/// Status account's profile status define
type Status int8

const (
	StatusNone          Status = 0
	StatusWaitForVerify Status = 1
	StatusActive        Status = 2
	StatusSuspend       Status = 3
	StatusDeleted       Status = 4
)

var EnumNamesStatus = map[Status]string{
	StatusNone:          "None",
	StatusWaitForVerify: "WaitForVerify",
	StatusActive:        "Active",
	StatusSuspend:       "Suspend",
	StatusDeleted:       "Deleted",
}

var EnumValuesStatus = map[string]Status{
	"None":          StatusNone,
	"WaitForVerify": StatusWaitForVerify,
	"Active":        StatusActive,
	"Suspend":       StatusSuspend,
	"Deleted":       StatusDeleted,
}

func (v Status) String() string {
	if s, ok := EnumNamesStatus[v]; ok {
		return s
	}
	return "Status(" + strconv.FormatInt(int64(v), 10) + ")"
}
